# version: '3'
#
# services:
#   app:
#     build:
#       context: .
#     tty: true
#     volumes:
#       - ./:/app
#     environment:
#       - WATCHPACK_POLLING=true
#     command: sh -c "npm run dev"
#     ports:
#       - "80:3000"

version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm dev"
