name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setUp .env
        run: cp .env.example .env

      - name: setUp Docker
        run: docker compose up -d --wait

      - name: ESLint
        run: make npm_lint

      - name: Check TypeScript
        run: make npm_tsc
